language: node_js
node_js: 10
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower web-component-tester
  - bower i
  - ln -s app/bower_components bower_components
script:
  - wct
env:
  global:
    - "CXX='g++-4.8'"
after_success:
  - if: branch =~ /^release\/beta$/
    node tasks/release-beta.js
  - if: branch = master
    node tasks/release-stable.js
  - if: branch = develop
    node tasks/release-dev.js
