language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower web-component-tester
  - bower i
script:
  - wct
node_js:
  - stable
env:
  global:
    - "CXX='g++-4.8'"
