language: node_js
node_js: 10
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
env:
  global:
    - "CXX='g++-4.8'"
cache:
  apt: true
  directories:
    - $HOME/.cache/bower
    - $HOME/.npm
install:
  - npm i -g bower web-component-tester
  - bower i
before_script:
  - ln -s app/bower_components bower_components
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
jobs:
  include:
    - stage: Test
      script: wct
    - if: branch = master
      stage: Stable release
      script: node tasks/release-stable.js
    - if: branch = develop
      stage: Dev release
      script: node tasks/release-dev.js
    - if: branch =~ /^release\/beta$/
      stage: Beta release
      script: node tasks/release-beta.js
